export const PRODUCT_TYPES={
    ADD_CATEGORY:'ADD_CATEGORY',
    DELETE_CATEGORY:'DELETE_CATEGORY',
    INSERT_ALL_CATEGORY:'INSERT_ALL_CATEGORY',
    FIND_CATEGORY:'FIND_CATEGORY',
    EDIT_CATEGORY:'EDIT_CATEGORY',
    INSERT_ALL_PRODUCTS:'INSERT_ALL_PRODUCTS',
    ADD_PRODUCTS:'ADD_PRODUCTS',
    FIND_PRODUCT:'FIND_PRODUCT',
    EDIT_PRODUCT:'EDIT_PRODUCT',
    DELETE_PRODUCT:'DELETE_PRODUCT',
    GET_RELATED_PRODUCTS_FOR_CATEGORY:'GET_RELATED_PRODUCTS_FOR_CATEGORY',
    SEARCH_PRODUCTS:'SEARCH_PRODUCTS'
}