export const USERTYPES={
    SET_CURRENT_USER:'SET_CURRENT_USER',
    ADD_PRODUTC_TO_USER:'ADD_PRODUCT',
    SET_USER_IMAGE:'SET_USER_IMAGE',
    SET_IMAGE_URL:'SET_IMAGE_URL',
    LOG_OUT:'LOG_OUT',
    TOGGLE_RESERVED_PRODUCT_COUNT:'TOGGLE_RESERVED_PRODUCT_COUNT',
    DELETE_PRODUCT_FROM_CART:'DELETE_PRODUCT_FROM_CART',
    START_UPLOADING_USER_PICTURE:'START_UPLOADING_USER_PICTURE',
    SUCCESS_UPLOADING_USER_PICTURE:'SUCCESS_UPLOADING_USER_PICTURE',
    FAILURE_UPLOADING_USER_IMAGE:'FAILURE_UPLOADING_USER_IMAGE'
}