export const USERTYPES={
    SET_CURRENT_USER:'SET_CURRENT_USER',
    ADD_PRODUTC_TO_USER:'ADD_PRODUCT',
    SET_USER_IMAGE:'SET_USER_IMAGE',
    SET_IMAGE_URL:'SET_IMAGE_URL',
    LOG_OUT:'LOG_OUT'
}