import Head from "next/head";
import { Address, AddressContainer, BackgroundImage, Container, FormContainer, GuideButton, Hello, Icon, IconContainer, Paragraph, RegisterContianer, RegisterSection, RightSection, SiteName, Test, Title } from "../../styles/register/Register.style";
import Image from "next/image";
import MarketingIcon from '../../public/Sale.png';
import LoginForm from "../form/LoginForm";
import Link from "next/link";
import BackImage from '../../public/images/backimg.svg';
const Register=({type,submitForm})=>{


    return(
        <div>
            <Head>
            <title>{type==='login'?'login-page':'signup-page'}</title>
            <meta name="description" content="Generated by create next app" />
            <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital@1&display=swap" rel="stylesheet"></link>
        </Head>
        <Container>
            <BackgroundImage>
                <Image src={BackImage} layout='fill'/>
                <RegisterContianer>
            <RegisterSection>
                <IconContainer>
                    <SiteName>Digital-Marketing</SiteName>
                    <Icon>
                        <Image src={MarketingIcon}   alt="marketin-icon"/>
                    </Icon>
                </IconContainer>
                <Title>{type==='login'?'Login To Our Site':'Signup In Our Site'}</Title>
                <FormContainer>
                    <LoginForm type={type} submitForm={submitForm} ></LoginForm>
                </FormContainer>
                <AddressContainer>
                    <Address>hosseinfouladi20@gmail.com</Address>
                </AddressContainer>
            </RegisterSection>
            <RightSection>
                <Hello>Hello,Friends!</Hello>
                <Paragraph>
                    {type==='login'?'Fill up personal information and start jurney with us':'If you have already signed up,go login page'}
                </Paragraph>
                <Link href={type==='login'?'/signup':'/'}>
                    <GuideButton>{type==='login'?'Sign up':'Login'}</GuideButton>
                </Link>
            </RightSection>
        </RegisterContianer>
            </BackgroundImage>
        
        </Container>  
        </div>
    )

}
export default Register;